Ajout du profile de Fardi
OpenClassrooms-Student-Center/community pull request #735
Opened 2020-12-06 17:31 UTC by Fardi01

Nouveau dans le parcours développeur d'application iOS, je souhaite ajouter ma pierre à l'édifice.
Dans le projet 2, je doit me rajouter dans le site des étudiants. C'est ma première demande de pull request et j'espère que je n'ai rien oublié et que celle-ci sera validé. 😃

2020-12-07 11:16 UTC, yamaraja requested changes

2020-12-07 11:16 UTC, yamaraja commented on .travis.yml
> +  system_site_packages: true
You shouldn't modify the travis file

2020-12-07 11:16 UTC, yamaraja commented on content/students/fardi.md
> +    Issus d'un milieu commerciale, j'ai découvert le métier de développeur un peu par
Should be "commercial"

2020-12-07 11:16 UTC, yamaraja commented on content/students/fardi.md
> +    intéressé et j'ai notament suivi des formations pour apprendre à créer des sites
Should be "notamment"

2020-12-07 11:16 UTC, yamaraja commented on content/students/fardi.md
> +    développeur iOS et me spécialiser dedans. J'ai toujours été dans l'eco systeme
"de me spécialiser". 
"dedans" can also be changed.

2020-12-07 11:16 UTC, yamaraja commented on content/students/fardi.md
> +    d'apple, je touve normal et excitant de pouvoir développer mes idées et créer mes
"trouve"

2020-12-07 11:16 UTC, yamaraja commented on content/students/fardi.md
> +    finished: true
Remove this bloc as you haven't started the project

2020-12-07 11:41 UTC, Fardi01 commented on .travis.yml
> +  system_site_packages: true
Done !

2020-12-07 11:41 UTC, Fardi01 commented on content/students/fardi.md
> +    Issus d'un milieu commerciale, j'ai découvert le métier de développeur un peu par
Done !

2020-12-07 11:41 UTC, Fardi01 commented on content/students/fardi.md
> +    intéressé et j'ai notament suivi des formations pour apprendre à créer des sites
Done !

2020-12-07 11:41 UTC, Fardi01 commented on content/students/fardi.md
> +    développeur iOS et me spécialiser dedans. J'ai toujours été dans l'eco systeme
Done !

2020-12-07 11:41 UTC, Fardi01 commented on content/students/fardi.md
> +    d'apple, je touve normal et excitant de pouvoir développer mes idées et créer mes
Done !

2020-12-07 11:41 UTC, Fardi01 commented on content/students/fardi.md
> +    finished: true
Done !

2020-12-07 11:49 UTC, Fardi01 reviewed
Rectifications are made

2020-12-07 11:49 UTC, Fardi01 commented on .travis.yml
> +  system_site_packages: true
Lines removed !

2020-12-08 13:11 UTC, yamaraja approved these changes

2020-12-11 22:58 UTC, closed without merging

2020-12-11 22:59 UTC, Fardi01 commented
Not working